title: Rapid Annotator
description: The blog is about my updates on the progess on the Google Code of Summer's project, Rapid Annotator.

show_downloads: true

baseurl: "/GSoC-Blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://guptavaibhav18197.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Vaibhav Gupta"
image: /thumbnail-jumbo.png
twitter:
  # username: vaibhavgupta
#  site:
facebook:
  #publisher: 1592372034171500
  profile_id: vaibhav.gupta.71
  app_id: 1798910940422432 # cayman-blog
  #authors: vaibhav
#  admins:
