title: Multilingual Neural Machine Translation for TV News
description: This blog is about my progress on my GSoC'18 project.

show_downloads: true

baseurl: "/gsoc_blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://vikrant97.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Vikrant Goyal"
image: /thumbnail-jumbo.png
twitter:
  # username: vikrant97
#  site:
#facebook:
  #publisher: 1592372034171500
  profile_id: 
  app_id:  # cayman-blog
  #authors: vaibhav
#  admins:
